import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Set;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Scanner;
import java.util.concurrent.*;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;


/**
 * Multithreaded Chat Server
 * Works with:
 *              PrintWriter/Scaner: in/out (println correspondation system)
 *              FLAGS: SUBMITNAME, NAMEACCEPTED, MESSAGE, COORDINATOR, MEMBERS
 *                      - at the begining of every output.
 *                      - generated by Server
 *                      - interpreted by Client
 *              CLIENT HANDLER: main handler
 *                      - run function to start client handler
 *                      - handles connect/disconnect, chat system (everithing)
 *                      - try/catch/finally
 *                          - try: handle login & chat
 *                          - finally: handle disconnect
 */
public class ChatServer {

    // names(Set) - stores usernames
    private static Set<String> names = new HashSet<>();

    // coordinator - username of coordinator
    private static String coordinator = null;

    // writers  - used to send messages
    //          - dictionary {name : PrintWriter}
    private static HashMap<String, PrintWriter> writers = new HashMap<>();

    // Start the Server
    public static void main(String[] args) throws Exception {
        System.out.println("The chat server is running...");
        ExecutorService pool = Executors.newFixedThreadPool(100);
        try (ServerSocket listener = new ServerSocket(59001)) {
            while (true) {
                pool.execute(new Handler(listener.accept()));
            }
        }
    }

    /**     CLIENT HANDLER     */
    private static class Handler implements Runnable {
        private String name;
        private Socket socket;
        private Scanner in;
        private PrintWriter out;
        public Handler(Socket socket) {
            this.socket = socket;
        }


        /**             RUN
         *  try:    JOIN & CHAT handelers
         *              Name Creation
         *              Messages
         *  finaly: DISCONNECT   handeler
         */
        public void run() {
            /**     JOIN & CHAT
             *  when someone connects he is repeatedly asked to submit username, until a uniqueone is given and accepted
             *  if first to join, get notified about it
             *  with every join we update the coordinator & members for all clients
             *  messages are exchanged either privately or with the group
             */
            try {
                in = new Scanner(socket.getInputStream());
                out = new PrintWriter(socket.getOutputStream(), true);

                // Handle name creation
                while (true) {
                    out.println("SUBMITNAME");
                    name = in.nextLine();
                    synchronized (names) {
                        if (!name.isEmpty() && !names.contains(name)) {
                            names.add(name);
                            if (coordinator == null) {
                                coordinator = name;
                            }
                            break;
                        }
                    }
                }

                // Flag -> NAME ACCEPT
                out.println("NAMEACCEPTED " + name);
                System.out.println(name + " joined");

                // Send: Flag -> MESSAGE "<name> has joined <time>"
                for (HashMap.Entry<String, PrintWriter> writer : writers.entrySet()) {
                    DateTimeFormatter hhmm = DateTimeFormatter.ofPattern("HH:mm");
                    LocalTime time = LocalTime.now();
                    writer.getValue().println("MESSAGE " + name + " has joined (" + time.format(hhmm) + ")");
                }
                // Add writer {name: PrintWriter}
                writers.put(name, out);
                // if: First message + add coordinator
                if (names.size() == 1) {
                    DateTimeFormatter hhmm = DateTimeFormatter.ofPattern("HH:mm");
                    LocalTime time = LocalTime.now();
                    writers.get(name).println("MESSAGE You are the first to join and the coordinator of this chat (" + time.format(hhmm) + ")");
                    writers.get(name).println("COORDINATOR " + coordinator);
                // else: Send ALL: Flag -> COORDINATOR, MEMBERS
                } else {
                    for (HashMap.Entry<String, PrintWriter> writer : writers.entrySet()) {
                        writer.getValue().println("COORDINATOR " + coordinator);
                        writer.getValue().println("MEMBERS " + names);
                    }
                }
                // Handle messages + time
                while (true) {
                    String input = in.nextLine();
                    // private messages (pm)
                    if (input.startsWith("/[")) {
                        DateTimeFormatter hhmm = DateTimeFormatter.ofPattern("HH:mm");
                        LocalTime time = LocalTime.now();
                        String toName = new String(input.substring(input.indexOf("[")+1, input.indexOf("]")));
                        writers.get(toName).println("MESSAGE " + name + "(pm)(" + time.format(hhmm) + "): " + input.substring(input.indexOf("]")+1));
                        writers.get(name).println("MESSAGE pm to " + toName + "(" + time.format(hhmm) + "): " + input.substring(input.indexOf("]")+1));
                    // group messages
                    } else {
                        for (HashMap.Entry<String, PrintWriter> writer : writers.entrySet()) {
                            DateTimeFormatter hhmm = DateTimeFormatter.ofPattern("HH:mm");
                            LocalTime time = LocalTime.now();
                            writer.getValue().println("MESSAGE " + name + "(" + time.format(hhmm) + "): " + input);
                        }
                    }
                }
            } catch (Exception e) {
                System.out.println(name + " is disconecting");
            /**     DISCONNECT
             *  disconects the user and changes the coordinator if needed
             *  notifies everyone about the changes
             */
            } finally {
                // Remove writer
                if (out != null) {
                    writers.remove(out);
                }
                // Handle Leaving
                if (name != null) {
                    names.remove(name);
                    writers.remove(name);
                    // if COORDINATOR
                    if (name == coordinator) {
                        if (names.isEmpty()){
                            coordinator = null;
                        }
                        for (HashMap.Entry<String, PrintWriter> writer : writers.entrySet()) {
                            DateTimeFormatter hhmm = DateTimeFormatter.ofPattern("HH:mm");
                            LocalTime time = LocalTime.now();
                            coordinator = names.iterator().next();
                            writer.getValue().println("MESSAGE " + name + " has left. The new coordinator is: " + coordinator + "(" + time.format(hhmm) + ")");
                            writer.getValue().println("COORDINATOR " + coordinator);
                            writer.getValue().println("MEMBERS " + names);
                        }
                    } else {
                    // if MEMBER
                        for (HashMap.Entry<String, PrintWriter> writer : writers.entrySet()) {
                            DateTimeFormatter hhmm = DateTimeFormatter.ofPattern("HH:mm");
                            LocalTime time = LocalTime.now();
                            writer.getValue().println("MESSAGE " + name + " has left (" + time.format(hhmm) + ")");
                            writer.getValue().println("COORDINATOR " + coordinator);
                            writer.getValue().println("MEMBERS " + names);
                        }
                    }

                }
                // Close Socket
                try { socket.close(); System.out.println(name + " disconected");
                } catch (IOException e) {}
            }
        }
    }
}
